### ISSUE TITLE
Add a way to add to-do's like this directly from Kountdown.

### ISSUE THREAD

**Issue by Lokosmos** [flashcactus/kountdown#16]
Everyone can help!

**Comment by flashcactus** [comment]
har har. Willie has a github module that does precisely this.

**Comment by Lokosmos** [comment]
Well great! Set it up!

**Comment by flashcactus** [comment]
Unfortunately I couldn't make it work. Additionally, it posts them all with one user

**Comment by Lokosmos** [comment]
Ya... but that would be part of the fun! (the spamming)

**Comment by Lokosmos** [comment]
Aww...
