### ISSUE TITLE
Through the use of markov chains, and whatever would be used for that topic derivation thing, add a function to try to figure out what a person was last talking about.

### ISSUE THREAD

**Issue by Lokosmos** [flashcactus/kountdown#19]
It'll be like an individual sitcom!

**Comment by flashcactus** [comment]
Markov chains are only useful for generating new content. Also, I'm working on this as a prerequisite for context-sensitive markoving. Unfortunately it won't be able to actually tell what that was about, just pull the most significant (hopefully) keywords and talk about something related.

**Comment by flashcactus** [comment]
closing for now, as this doesn't deem particularly useful. Humans are better at interpreting the last message anyway, and entertainment purposes do not require doing this kind of thing automatically.
